name: Cypress Tests
on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1, 2, 3, 4] # Índices para splits
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests (split)
        run: |
          npx cypress run --env split=ci,splitIndex=${{ matrix.containers }},splitTotal=5

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results-${{ matrix.containers }}
          path: cypress/results/ # Ajuste para a pasta onde seus resultados estão
