name: End-to-end tests
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # paralelismo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev # sobe o servidor (serve -s dist -p 3000)
          wait-on: http://localhost:3000 # espera o servidor estar pronto
          wait-on-timeout: 120 # tempo máximo de espera (segundos)
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
